id: IAFE9D134
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:52:39+00:00'
last_modified: '2022-06-08T11:30:08.555321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22443
  title: དཀྱིལ་འཁོར་ཐམས་ཅད་ཀྱི་ངོ་བོ་བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རྒྱ་མཚོ་སོགས།  ༼རྫོགས་ཆེན་ཤྲཱི་སིཾ་ཧའི་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1BBB:
      image_group_id: I1KG22459
      title: ''
      total_pages: 902
      order: 1
      base_file: 1BBB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
