id: P009504
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:33:31.207075
source_metadata:
  id: bdr:W1KG22443
  title: དཀྱིལ་འཁོར་ཐམས་ཅད་ཀྱི་ངོ་བོ་བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རྒྱ་མཚོ་སོགས།  ༼རྫོགས་ཆེན་ཤྲཱི་སིཾ་ཧའི་པར་མ།༽
  author: ''
  volumes:
    030afa5a1a6248439197478966580d35:
      image_group_id: I1KG22459
      title: ''
      volume_number: 1
      total_pages: 902
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
