id: P009504
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22443
  title: དཀྱིལ་འཁོར་ཐམས་ཅད་ཀྱི་ངོ་བོ་བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རྒྱ་མཚོ་སོགས།  ༼རྫོགས་ཆེན་ཤྲཱི་སིཾ་ཧའི་པར་མ།༽
  author: ''
  volumes:
    030afa5a1a6248439197478966580d35:
      image_group_id: I1KG22459
      title: ''
      volume_number: 1
      total_pages: 902
