id: opecha:P009504
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22443
  title: དཀྱིལ་འཁོར་ཐམས་ཅད་ཀྱི་ངོ་བོ་བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རྒྱ་མཚོ་སོགས།  ༼རྫོགས་ཆེན་ཤྲཱི་སིཾ་ཧའི་པར་མ།༽
  volume: ''
  author: ''
